// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx5lGEDY2cilADTB3XltufvkWIGW-sfJg',
    appId: '1:1052489035898:web:d38077e4784addb2740bc3',
    messagingSenderId: '1052489035898',
    projectId: 'new-repository-3d1dd',
    authDomain: 'new-repository-3d1dd.firebaseapp.com',
    storageBucket: 'new-repository-3d1dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChadooQ-kSSFk0oLR18qTtCrP48N6wZhk',
    appId: '1:1052489035898:android:62cfddc19c0dc1ca740bc3',
    messagingSenderId: '1052489035898',
    projectId: 'new-repository-3d1dd',
    storageBucket: 'new-repository-3d1dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCegDlcctWyi6DXqgG2V-ZxpMZznt08Nl8',
    appId: '1:1052489035898:ios:e762872ec305c8ee740bc3',
    messagingSenderId: '1052489035898',
    projectId: 'new-repository-3d1dd',
    storageBucket: 'new-repository-3d1dd.firebasestorage.app',
    iosBundleId: 'com.example.newInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCegDlcctWyi6DXqgG2V-ZxpMZznt08Nl8',
    appId: '1:1052489035898:ios:e762872ec305c8ee740bc3',
    messagingSenderId: '1052489035898',
    projectId: 'new-repository-3d1dd',
    storageBucket: 'new-repository-3d1dd.firebasestorage.app',
    iosBundleId: 'com.example.newInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx5lGEDY2cilADTB3XltufvkWIGW-sfJg',
    appId: '1:1052489035898:web:e9a04f4289579e71740bc3',
    messagingSenderId: '1052489035898',
    projectId: 'new-repository-3d1dd',
    authDomain: 'new-repository-3d1dd.firebaseapp.com',
    storageBucket: 'new-repository-3d1dd.firebasestorage.app',
  );
}
